### PR TITLE
:wrench: Add new emojis

### PR DESCRIPTION
**Pull request by gastrid**

### CODE REVIEW

**Comment by Mehdi-Hp** [comment]
Can you merge this please?

**Comment by gastrid** [comment]
Hi, I can't, sadly, we've got to wait for the repo owner to do it.

**Comment by Mehdi-Hp** [comment]
Oh, I know. the audience was the owner. 👍

**Comment by gastrid** [comment]
Sent him an email. Hopefully that'll be merged soon!

**Comment by arvinxx** [comment]
I didn't check it. I'm sorry. I will merge it now.

**Comment by Mehdi-Hp** [comment]
@arvinxx It's broken. you should use uderscore, not dash:
```
':loud-sound:'
':see-no-evil:'
':camera-flash:'
':wheel-of-dharma:'
```

**Pull request merged**
